### ISSUE TITLE
Dice team logo

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/dice-cyfronet.github.io#25]
@bwilk please talk with your sister about dice team webpage logo

**Comment by Nuanda** [comment]
What do you mean? Do we want a new DICE group logo?

**Comment by mkasztelnik** [comment]
Maybe not new but refreshed version. Bartek was mentioning that his sister (UI designer) can help us to create logo which will fit to http://dice-team.github.io look and feel.

**Comment by Nuanda** [comment]
I see.

**Comment by mpawlik** [comment]
@bwilk any news?

**Comment by mkasztelnik** [comment]
@bwilk any news?

**Comment by mkasztelnik** [comment]
@bwilk any news?

**Comment by mpawlik** [comment]
My suggestion: ![dicelogo](http://i.huffpost.com/gen/707282/thumbs/o-DICELOGO-570.jpg?4)

**Comment by Nuanda** [comment]
Magritte FTW :) :+1:

**Comment by mkasztelnik** [comment]
Perfect :heart:

**Comment by mkasztelnik** [comment]
I was experimenting with a logo, but it does not look good in the header.

![dice-logo](https://cloud.githubusercontent.com/assets/1265430/13360086/aadc762c-dcb7-11e5-9fe8-2819cdc12c4b.png)

If not response from @bwilk with better solution will appear in next week I propose to close this issue.

**Comment by Nuanda** [comment]
:+1:

**Comment by mkasztelnik** [comment]
@Nuanda :+1: for closing this issue or for using dice logo?

**Comment by Nuanda** [comment]
both
