### ISSUE TITLE
Can we add MetaBiobank into portfolio section?

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/dice-cyfronet.github.io#27]
@Nuanda I saw [MetaBiobank](https://biobank.plgrid.pl/) already deployed into plgrid infrastructure. Can we you add it into portfolio section?

**Comment by Nuanda** [comment]
Not yet - still going through the audit procedure.

**Comment by mkasztelnik** [comment]
@Nuanda and now? Is it ready?

**Comment by Nuanda** [comment]
Sure.

**Comment by Nuanda** [comment]
What should I do?

**Comment by mkasztelnik** [comment]
Add something similar to https://github.com/dice-cyfronet/dice-cyfronet.github.io/blob/master/_posts/2015-05-20-plgapp.markdown and 2 project pictures, similar to: https://github.com/dice-cyfronet/dice-cyfronet.github.io/blob/master/img/portfolio/plgapp-thumbnail.png and https://github.com/dice-cyfronet/dice-cyfronet.github.io/blob/master/img/portfolio/plgapp.png (please use the same picutres sizes as for plgapp).
